export const ROUTES = {
  LOGIN:             '/login',
  DASHBOARD:         '/',
  TRANSACTIONS:      '/transactions',
  PORTFOLIOS:        '/portfolios',
  PORTFOLIO:         (id: string) => `/portfolios/${id}`,
  PROPERTIES:        '/properties',
  PROPERTY:          (id: string) => `/properties/${id}`,
  PARTNERS:          '/partners',
  PARTNER:           (id: string) => `/partners/${id}`,
  PARTNER_DETAIL:    (id: string) => `/partners/${id}`,
  REPORTS:           '/reports',
  CAPITAL:           '/capital',
  CAPITAL_DETAIL:    (accountId: string) => `/capital/${accountId}`,
  SETTLEMENTS:        '/settlements',
  SETTLEMENT_DETAIL: (id: string) => `/settlements/${id}`,
  JOURNAL:           '/journal',
  JOURNAL_REVIEW:    '/journal-review',
  TRIAL_BALANCE:     '/reports/trial-balance',
  SETTINGS:          '/settings',
  SETTINGS_PEOPLE:   '/settings/people',
  SETTINGS_EXCHANGE: '/settings/exchange-rates',
  SETTINGS_COMPANY:  '/settings/company',
} as const;
